### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by droualdes** [andrewshell/baseurltest#1]
I'm new to Github, so I hope I'm putting this in the right place. If not, sorry! The following link is broken.

http://blog.andrewshell.org/baseurltest/

Error:

404 Not Found

Code: NoSuchKey
Message: The specified key does not exist.
Key: baseurltest/index.html
RequestId: 4EFCB49E6AE722E1
HostId: oFT6c0yUh8jKYSBPdOvB/wU45DDce9P+JUrHzwGn4p7R0BvGxDWzsMyZYOtyGHvylvfSXteicag=
An Error Occurred While Attempting to Retrieve a Custom Error Document

Code: NoSuchKey
Message: The specified key does not exist.
Key: error.html

**Comment by andrewshell** [comment]
Thanks for pointing that out.  I've updated the link to be the correct URL: http://andrewshell.github.io/baseurltest

**Comment by droualdes** [comment]
You’re welcome.
